name: sheepdog-etcd
services:
  ioutgt-build:
    image: ioutgt
    build: https://github.com/hreinecke/ioutgt.git#sheepdog
  target0:
    image: ioutgt
    hostname: ${TARGET0_NAME}
    network_mode: service:sheepdog-etcd-sheep0-1
    ports:
      - "127.0.0.1:4420:4420"
    command: /usr/sbin/ioutgt-nvme-tcp --io-threads 4 --listen 127.0.0.1:4420 --backend sheepdog:${SHEEP0_IP}:7000
  target1:
    image: ioutgt
    hostname: ${TARGET1_NAME}
    network_mode: service:sheepdog-etcd-sheep1-1
    ports:
      - "127.0.0.1:4421:4420"
    command: /usr/sbin/ioutgt-nvme-tcp --io-threads 4 --listen 127.0.0.1:4420 --backend sheepdog:${SHEEP1_IP}:7000
